import type { TaskResult } from '@quills/shared';
import type { AgentTaskInput, ModelProvider } from './provider';

export class MockProvider implements ModelProvider {
  readonly id = 'mock';

  async run(agentId: string, input: AgentTaskInput): Promise<TaskResult> {
    const packet = input.packet;
    const body = packet
      ? [
          `POV: ${packet.pov}`,
          `Goal: ${packet.chapterGoal}`,
          '',
          `${packet.pov} descended into the observatory with every breath counted against the three-minute limit of her glasslight.`,
          'Tovin followed, one hand on the wall and the other on the old siege-marked lock they had come to fear.',
          'When the tide machinery stirred awake, the Archive door answered with a groan that sounded almost human.',
        ].join('\n')
      : input.prompt;

    return {
      agentId,
      artifactType: agentId === 'prose-drafter' ? 'chapter_draft' : 'agent_output',
      title: `${agentId} result`,
      summary: 'Mock provider result generated for local desktop flow verification.',
      body,
      warnings: ['Generated by the mock provider, not a live Ollama model.'],
    };
  }
}
